### ISSUE TITLE
Need clarity on collection of additional network information

### ISSUE THREAD

**Issue by rohanaurora** [iovation/deviceprint-SDK-iOS#1]
- FraudForce.framework 5.0.2
- iOS 9.0 and higher

Hey there,

1. Can you please explain what specific collection of additional network information is sent to iovation's service? 

2. With `shouldEnableNetworkCalls` turned `false` does the FraudForceSDK make any specific API calls to iovation's servers?

```
/*!
 * Authorizes a network call to iovation's service that enables the collection of additional network
 * information. If this method returns NO or is not implemented then the SDK will not make network calls.
 *
 * @since v5.0.0
 *
 */
- (BOOL)shouldEnableNetworkCalls;
```

**Comment by mattr-io** [comment]
Hi Rohan - This repo is primarily for distribution to iovation customers. We recommend you direct your questions to your iovation Customer Success Rep or the iovation Integration Engineer that you are working with.
