### ISSUE TITLE
Support for Pods

### ISSUE THREAD

**Issue by ir2pid** [iovation/deviceprint-SDK-iOS#11]
We would like to get support for Pods instead of frameworks. Can you support us with that?

**Comment by PDXMobileTommy** [comment]
Howdy,

Based on our most recent review of the CocoaPods project in February 2020, we have determined that CocoaPods is not in a state that we can agree to support at this time.  Should this change in the future, we will make it known through our customer communications and updated read me files.

Cheers,
Tommy
