### ISSUE TITLE
Xcode 11 Unit tests '@testable import AppModule' issue

### ISSUE THREAD

**Issue by DNCGraef** [iovation/deviceprint-SDK-iOS#13]
Hi,

To work around the Xcode 11 build errors, your sample project suggests adding a build script to remove the built framework after the "embed frameworks" phase. 

However, if you have any test files with '@testable import MyAppName' directive, they fail to compile with a "Missing required module 'FraudForce'" error. 

What do you advise in this case?

<img width="1050" alt="Screenshot 2020-08-25 at 14 27 06" src="https://user-images.githubusercontent.com/1926380/91180606-d55da100-e6df-11ea-9db4-80d4d8bebb88.png">

**Comment by sara-porter-iovation** [comment]
Howdy! The "cleanup" step is to resolve an issue when alternating building between simulators and devices. If that's not an issue for the actions you're running, then it's ok to escape the step or remove it.

**Comment by Lucky1st** [comment]
@sara-porter-iovation I faced the same problem. The solution you suggested actually works. But if we are talking about testing on different simulators using CI, then your solution will not work. Perhaps this is due to another problem described in https://github.com/iovation/deviceprint-SDK-iOS/issues/16. How do you think switching to SPM for example will solve the problem?

**Comment by sara-porter-iovation** [comment]
Interesting! Switching between different simulators using Continuous Integration shouldn't be affected as the initial slimming script sets the library in the app for simulators. For example, for the first simulator, build with something like `xcodebuild build-for-testing` then following with running `xcodebuild test-without-building`  
Can you tell me if you're building on Catalina or Big Sur, Intel or M1, and if you're building for iOS or Universal?
For new features like SPM or others, please request them from your Customer Success engineer.  Thank you!

**Comment by Lucky1st** [comment]
Of course. I'm building on Big Sur using Intel x86 processor for iOS only.

Do I understand correctly the requests for features described in the issues will not be taken into development plan of the SDK  if there is no request from our Customer Success engineer?

**Comment by sara-porter-iovation** [comment]
Thank you for the build info! We don't daily watch Github while Customer Success engineer requests come in at a high priority.
