### ISSUE TITLE
Xcode 12.3 (12C33) 🛠 cannot build for simulators 📱

### ISSUE THREAD

**Issue by PH9** [iovation/deviceprint-SDK-iOS#16]
Found this error.

`/Users/w/directory/Project.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'FraudForce.framework' was built for iOS + iOS Simulator.`

**Comment by thanasak22** [comment]
workaround 

https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built

**Comment by evnik** [comment]
Hey @PH9 and everyone facing the same issue,
Could you please try to convert the `FraudForce.framework` to XCFramework using [this script](https://gist.github.com/evnik/6762d5c3a4b21f61f13b100e03b62c38), replace the framework in your project and let me know if it works? Thank you

**Comment by PH9** [comment]
> workaround
> 
> [stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built)

I do after this. And it works.
