### ISSUE TITLE
Xcode build fails for xcode 12.4

### ISSUE THREAD

**Issue by ljubiccica** [iovation/deviceprint-SDK-iOS#17]
Another Setup build script action is needed:

For Xcode 12 (and above), set Validate Workspace to Yes in the Build Settings tab (without it Building for iOS Simulator, but the linked framework 'FraudForce.framework' was built for iOS crash appears)

![validate-workspace](https://user-images.githubusercontent.com/8993679/112595047-2a929a00-8e0a-11eb-876f-dabfec7aa0fc.png)

**Comment by ashley-campbell-iovation** [comment]
Hello!

This is the correct action, thank you.

Ashley
