### ISSUE TITLE
Archive validation failed

### ISSUE THREAD

**Issue by SKerencic** [iovation/deviceprint-SDK-iOS#18]
We are having some issues with Archive validation. 
Is there anything that we missed?

<img width="724" alt="Screenshot 2021-03-30 at 16 43 33" src="https://user-images.githubusercontent.com/36759859/113008666-85642280-9177-11eb-8542-d500f112bd58.png">

Many thanks for your help.

**Comment by ashley-campbell-iovation** [comment]
Hello!

A suspicion is that you may not have ran the required slimming script. This script will remove the simulator x86 slice that is generally rejected by the App Store. Give this a try.

Thanks!
Ashley

**Comment by SKerencic** [comment]
@ashley-campbell-iovation that was my first thought too. But not sure that that's the issue. Based on the images below i think the script is running.

<img width="672" alt="Screenshot 2021-03-30 at 20 48 22" src="https://user-images.githubusercontent.com/36759859/113040857-945bcc80-9199-11eb-9a27-73fc6c5e430a.png">

<img width="780" alt="Screenshot 2021-03-30 at 20 54 34" src="https://user-images.githubusercontent.com/36759859/113041430-40051c80-919a-11eb-8368-a5368dfd4543.png">

**Comment by mark-sanvitale-iovation** [comment]
From those screenshots, it does appear that the script is running and producing a slimmed version of the FraudForce framework, as designed. Another thing to check is whether you are actually using the slimmed version of the framework in your application build. Specifically, steps 3 & 4 in the "Installation" section of the SDK README.

To directly confirm the state of the framework that is actually embedded into your built application, you can go into your application's app package and run
```
% file Frameworks/FraudForce.framework/FraudForce 
```
which will output this for an app built to run on device:
```
Frameworks/FraudForce.framework/FraudForce: Mach-O universal binary with 1 architecture: [arm64:Mach-O 64-bit dynamically linked shared library arm64]
Frameworks/FraudForce.framework/FraudForce (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```
and, alternatively, the framework embedded in an app that is built to run in a simulator, will contain only a macOS approrpiate architecture:
```
Frameworks/FraudForce.framework/FraudForce: Mach-O universal binary with 1 architecture: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64]
Frameworks/FraudForce.framework/FraudForce (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by SKerencic** [comment]
@mark-sanvitale-iovation we fixed the issue. We were using the wrong framework.
Many thanks for your help and time invested into it.

Best
