### ISSUE TITLE
How to decode blackbox string?

### ISSUE THREAD

**Issue by yizhi996** [iovation/deviceprint-SDK-iOS#19]

**Comment by ashley-campbell-iovation** [comment]
Hello!

The blackbox is for use by the iovation systems. Per our use contract, a client should not attempt to copy, modify, reverse engineer, decompile or disassemble any part of the software inclusive of the blackbox. If you have any questions about the contents of the blackbox, please reach out to your Integration Engineer or a Client Success representative.

Thanks,
Ashley
