### ISSUE TITLE
CocoaPod support

### ISSUE THREAD

**Issue by timrozum** [iovation/deviceprint-SDK-iOS#2]
Hello. Is there a reason this framework cannot be distributed via CocoaPods? I have used CocoaPods `vendored_frameworks` feature to distribute binary frameworks in the past. It seems like install would be a lot simpler which would be a win-win for customers and iovation. Or am I missing something? Thanks!

**Comment by mattr-io** [comment]
Hi - Thanks for the comment. CocoaPods integration and distribution is on our roadmap for later this year.

**Comment by timrozum** [comment]
That's great thanks!

**Comment by zackdotcomputer** [comment]
Wanted to check in on this since I agree it'd be great to have.

**Comment by PiotrWpl** [comment]
Hi!

Any progress on this one? Lack of CocoPods support is complicating some stuff for us :/
