### ISSUE TITLE
ObjC symbol obfus only? Are you serious?

### ISSUE THREAD

**Issue by Lessica** [iovation/deviceprint-SDK-iOS#21]
This framework is not secure. All blackbox attrs can be easily modified via this method:

```objective-c
/* @class NSData */
-(void *)cgzthSymbolZeroOne 
```

**Comment by mark-sanvitale-iovation** [comment]
Symbol obfuscation is not a perfect solution to the issue of binary or runtime tampering, but it does an effective job at hindering the process, as demonstrated by the content of this issue.

If you have more detailed inquiries then you should contact the customer support representative for your iovation/TransUnion account. Thanks!
