### ISSUE TITLE
Jenkins job always build fail

### ISSUE THREAD

**Issue by swy680614** [iovation/deviceprint-SDK-iOS#22]
Hi
I create Jenkins job to build my project, but always fail.
By using command line is success.
Please help.
![Screen Shot 2021-06-30 at 1 02 32 PM](https://user-images.githubusercontent.com/8295029/123906928-a111db80-d9a7-11eb-854d-38add1abdd0c.png)
![Screen Shot 2021-06-30 at 1 05 54 PM](https://user-images.githubusercontent.com/8295029/123906935-a4a56280-d9a7-11eb-87b6-fa9f4621ec4c.png)

**Comment by sara-porter-iovation** [comment]
Hello! 
I suspect your keychain isn't unlocked for your Jenkins build project.  There are some helpful items in StackOverflow for that signing error - https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen

Cheers,
Sara
