### ISSUE TITLE
Hi, is the "Access WiFi Information" entitlement still required?

### ISSUE THREAD

**Issue by DigitalZebra** [iovation/deviceprint-SDK-iOS#24]
Hello,
In the process of integrating this SDK with our app, we encountered step 6 from the README:

> For Xcode 10 (and above), allow Device Risk to collect wireless network information: * Configure your app to include the "Access WiFi Information" capability. * Turning the capability on for your application target in Xcode 10 (and above) will update the app's entitlements file and provisioning profile.
> 
> This entitlement is not required for (and breaks automatic code signing of) apps built by earlier versions of Xcode.

Adding the `com.apple.developer.networking.wifi-info` entitlement can be problematic for a few reasons. So, we're curious if this step can be omitted? Will a blackbox value still be generated if this entitlement isn't granted?

Thanks!

**Comment by sara-porter-iovation** [comment]
Hello!
A blackbox will still be generated without the entitlement. 

Cheers,
Sara
