### ISSUE TITLE
ITMS-90562: Invalid Bundle 

### ISSUE THREAD

**Issue by michaelrizzello** [iovation/deviceprint-SDK-iOS#25]
Apple continue to mark our builds as Invalid Binary, the app compiles and runs but does not pass the apple checks. I've followed the Submission Preparation and we're getting the same result.

**Comment by ashley-campbell-iovation** [comment]
Hello!

It sounds like there is a possibility that the slim-build-frameworks.sh isn't being ran (ie: the simulator architecture slice is not being stripped from your build)
https://github.com/iovation/deviceprint-SDK-iOS/tree/v5.2.0

Could you double check your steps for running the script using the readme on the tagged release above?

- Ashley

**Comment by michaelrizzello** [comment]
Should we not be using the master branch?

**Comment by ashley-campbell-iovation** [comment]
Master branch is fine but, as noted at the top of the pages, we are in slight transition with our documentation rebranding which seems to be the gap in this situation. I recommend reading the readmes specific to the release you are targeting specifically.

- Ashely

**Comment by michaelrizzello** [comment]
Thanks Ashley!

**Comment by michaelrizzello** [comment]
Looks like this is still happening. I just noticed that the framework wasn't imported into the project

**Comment by sara-porter-iovation** [comment]
Hello! Are you using the XCFramework or the Framework from https://github.com/iovation/deviceprint-SDK-iOS/releases ?  I'd recommend the XCFramework as it doesn't require the slimming script script or other steps.

**Comment by michaelrizzello** [comment]
We were using the CXFramework and we were getting the exact same issue. We followed the recommendations from Ashley above and used v5.2.0, and same result.

**Comment by sara-porter-iovation** [comment]
Gotcha. Could you create a CGQ ticket with the macOS and Xcode versions and whether it's built on Intel or M1 along with build logs and information from:
- Product menu -> Archive
- Archive -> Validate App
- Check your appropriate options
- And then "Validate" button
- The results will check signing, embedding (from the Project -> General -> "Frameworks, Libraries..."), and other details.
Thanks!

**Comment by ashley-campbell-iovation** [comment]
CGQ Tickets are created by reaching out to your Customer Success agent or Integration engineer.

- Ashley
