### ISSUE TITLE
Missing arm_64 support in the XCFramework build for simulator 

### ISSUE THREAD

**Issue by simonpierreroy** [iovation/deviceprint-SDK-iOS#27]
<img width="679" alt="Screen Shot 2021-09-10 at 1 54 48 PM" src="https://user-images.githubusercontent.com/44030728/132896787-60776766-0359-4052-b566-3aa99884c052.png">

Please add arm_64 (M1) support for simulator build. (Potentially by updating `EXCLUDED_ARCHS ` ;)  )

**Comment by fatih-emre** [comment]
I am having such issue while running the CI: 
```
[16:18:33] :	 [Step 2/5] Undefined symbols for architecture arm64:
[16:18:33] :	 [Step 2/5]   "_OBJC_CLASS_$_FraudForce", referenced from:
[16:18:33] :	 [Step 2/5]       objc-class-ref in xxxx.o
[16:18:33] :	 [Step 2/5]       objc-class-ref in xxx.o
[16:18:33] :	 [Step 2/5] ld: symbol(s) not found for architecture arm64
```

**Comment by sara-porter-iovation** [comment]
Good day! Our current release doesn't include an M1 simulator slice (it is being worked on!) and a flag is needed to force Rosetta while building on M1 hardware to use the x86 slice for simulators. 
In your build target -> Excluded Architectures -> exclude arm64 from iOS Simulator SDK.
For further help, please contact your integration engineer. Thanks you!

**Comment by karthikkeyan** [comment]
@sara-porter-iovation Is there a timeline for the m1 release(i.e. without excluding the `arm64` in build settings).

**Comment by metcheverr-chwy** [comment]
We would be interested in native arm64 simulator support as well. Apple is quickly ending the sale of x86 machines, and having to run under Rosetta is a performance penalty.

**Comment by matheusalano** [comment]
@sara-porter-iovation @mark-sanvitale-iovation any updates on this?

**Comment by sara-porter-iovation** [comment]
Today!  Thank you for your patience, today's release of the SDK and XCFramework include an M1 simulator slice.

**Comment by metcheverr-chwy** [comment]
Thank you so much! @sara-porter-iovation

**Comment by sara-porter-iovation** [comment]
5.3.0 XCFramework includes M1 simulator architecture
