### ISSUE TITLE
FraudForce.blackbox() returns payload without device info

### ISSUE THREAD

**Issue by Eugene-Novikov** [iovation/deviceprint-SDK-iOS#29]
After calling FraudForce.blackbox() I have got result without device information (I’ve run your swift example – result is correct)

My response after blackbox decoding: 

{
    "id": "3a66b11a-5c81-4e8a-bcfa-9429e49e58bd",
    "result": "A",
    "statedIp": "1.1.1.1",
    "accountCode": "Test",
    "trackingNumber": 134964117364296414,
    "details": {
        "statedIp": {
            "address": "1.1.1.1",
            "isp": "CLOUDFLARE",
            "ipLocation": {
                "city": "SYDNEY",
                "country": "AUSTRALIA",
                "countryCode": "AU",
                "latitude": -33.86714,
                "longitude": 151.20711,
                "region": "NEW SOUTH WALES"
            },
            "parentOrganization": "APNIC AND CLOUDFLARE DNS RESOLVER PROJECT",
            "source": "subscriber"
        },
        "realIp": {
            "address": "1.1.1.1",
            "isp": "CLOUDFLARE",
            "ipLocation": {
                "city": "SYDNEY",
                "country": "AUSTRALIA",
                "countryCode": "AU",
                "latitude": -33.86714,
                "longitude": 151.20711,
                "region": "NEW SOUTH WALES"
            },
            "parentOrganization": "APNIC AND CLOUDFLARE DNS RESOLVER PROJECT",
            "source": "subscriber"
        },
        "ruleResults": {
            "score": 0,
            "rulesMatched": 0
        }
    }
}

May you know a reason?

**Comment by sara-porter-iovation** [comment]
Hello!  Please work with your Customer Success engineer for integration debugging help.  Thank you!

**Comment by Eugene-Novikov** [comment]
It was my fail, just copied the value in debug and it was trimmed to the first 1024 characters
