### ISSUE TITLE
Archive/Codesigning Failure

### ISSUE THREAD

**Issue by ChrisBGriffith** [iovation/deviceprint-SDK-iOS#3]
Using the latest GM version of Xcode (10.3), and with the post-archive run script in place, the process of code signing our app is failing. I have inspected the archive and the symbol maps are all in the correct folder.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/6865246/61904358-4e426600-aeec-11e9-9c62-861648427594.png">

``` Writing entitlements for <IDEDistributionItem: 0x7ff308ef9a20 'com.iovation.FraudForce' '<DVTFilePath:0x7ff308170fe0:'/Users/chris/Library/Developer/Xcode/Archives/2019-07-25/Joust 7-25-19, 2.24 PM.xcarchive/Products/Applications/Joust.app/Frameworks/FraudForce.framework'>'> to: /var/folders/l0/0207280946q5pv1cc7_p33xh0000gn/T/XcodeDistPipeline.~~~S1Ie8F/entitlements~~~eGpgwB
Running /usr/bin/codesign '-vvv' '--force' '--sign' '4E1A48200D84E0F84A0F7DDF337C018A87B35241' '--entitlements' '/var/folders/l0/0207280946q5pv1cc7_p33xh0000gn/T/XcodeDistPipeline.~~~S1Ie8F/entitlements~~~eGpgwB' '--preserve-metadata=identifier,flags,runtime' '/var/folders/l0/0207280946q5pv1cc7_p33xh0000gn/T/XcodeDistPipeline.~~~S1Ie8F/Root/Payload/Joust.app/Frameworks/FraudForce.framework'
/var/folders/l0/0207280946q5pv1cc7_p33xh0000gn/T/XcodeDistPipeline.~~~S1Ie8F/Root/Payload/Joust.app/Frameworks/FraudForce.framework: replacing existing signature
/var/folders/l0/0207280946q5pv1cc7_p33xh0000gn/T/XcodeDistPipeline.~~~S1Ie8F/Root/Payload/Joust.app/Frameworks/FraudForce.framework: code object is not signed at all
/usr/bin/codesign exited with 1```

**Comment by mattr-io** [comment]
Thank you for the feedback. Did your work with the iovation Integration Engineer solve the issue?

**Comment by Epilef89** [comment]
I have the same error when I try to upload to the App Store. My project is an SDK with Fraud force and the distribution is with CocoaPods. Can you help me?

**Comment by yasodha-r** [comment]
I too have the same issue. @mattr-io  How this can be fixed?

**Comment by sara-porter-iovation** [comment]
Hello! Please make sure you're using the[ XCFramework](https://github.com/iovation/deviceprint-SDK-iOS/releases/download/v5.2.0/FraudForce.xcframework.zip). The [Readme](https://github.com/iovation/deviceprint-SDK-iOS) has been updated with directions to both upgrade and for new integrations.  For further help, please work with your integration engineer. Thank you!

**Comment by yasodha-r** [comment]
@sara-porter-iovation thank you so much. Readme update fixed my issue.
