### ISSUE TITLE
adding FraudForce.xcframework from script

### ISSUE THREAD

**Issue by expcapitaldev** [iovation/deviceprint-SDK-iOS#30]
I see from your documentation next text about our sdk "FraudForce.xcframework":
**Drag and drop** (or select the "+" button) to add the FraudForce.xcframework into the "Frameworks, Libraries, and Embedded Content" section of the "General" pane of the Xcode target editor.
Why you did not have script for that for clients whom want to use your product using build machine with a lot of pipelines and etc?
pld add script without manual **Drag and drop**

**Comment by expcapitaldev** [comment]
@mark-sanvitale-iovation 
@TannerVolz 
@ashley-campbell-iovation 
pls check, it is important issue for your client whom want to use your sdk

**Comment by mark-sanvitale-iovation** [comment]
The documentation for installing the SDK into an app is not comprehensive. Rather, it details the most common integration scenario; namely, an individual directly using the Xcode IDE to add the framework to their app project. Adventurous engineers can, naturally, come up with many other ways to address this integration task. That is an exercise best left to the adventurous engineer, not general-purpose documentation.

Note, however, that my professional advice is to avoid making this step overly complicated. Dragging & dropping is a very simple, manual step that results in editing the project file (`.xcodeproj` bundle) in a future-proof manner (i.e. does not presume knowledge of the Apple-internal project file format) that needs to be done _only one time_. Subsequently, one could script the updating of the installed SDK if that is desirable, but, again, this is a simple operation (overwrite the `.xcframework` bundle/directory with a different version), thus, scripting seems, to me, to be overcomplicating things.

You are welcome to contact your TransUnion Customer Success / Integration representative for more specific assistance.
