### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by tobatha** [iovation/deviceprint-SDK-iOS#33]
Just wondering if this SDK supports CocoaPods, which will be a lot convenient to add it simply as Pod, also right now CocoaPods supports precompiled binary package, so it won't be so complicated to targeting the release zip as the source

**Comment by aenglander** [comment]
Unfortunately, CocoaPods is not an option. CocoaPods requires providing source code which we cannot do. We may have support for Carthage in the future although a Carthage implementation has a number of hurdles specific to this library which have prevented providing Carthage based deployment. It's something we reevaluate from time to time to see if a newer version adds the functionality we need to make it work.

**Comment by tobatha** [comment]
@aenglander Hi there, currently CocoaPods already supported precompiled binary lib/frameworks to public which means any commerical SDKs can host their libs to public without having to give up any source codes at all, here's the [reference ](https://guides.cocoapods.org/syntax/podspec.html#vendored_frameworks) for your consideration, thanks!

Here's the example i grabbed from SO, the source could be pointing right to your releases on github
```
Pod::Spec.new do |s|
  s.name         = "EstimoteSDK"
  s.version      = "1.3.0"
  s.summary      = "iOS library for Estimote iBeacon devices"
  s.homepage     = "http://estimote.com"
  s.author       = { "Estimote, Inc" => "contact@estimote.com" }
  s.platform     = :ios 
  s.source       = { :git => "https://github.com/Estimote/iOS-SDK.git", :tag => "  {s.version}" }
  s.source_files =  'EstimoteSDK/Headers/*.h'
  s.preserve_paths = 'EstimoteSDK/libEstimoteSDK.a'
  s.vendored_libraries = 'EstimoteSDK/libEstimoteSDK.a'
  s.ios.deployment_target = '7.0'
  s.frameworks = 'UIKit', 'Foundation', 'SystemConfiguration', 'MobileCoreServices', 'CoreLocation'
  s.requires_arc = true
  s.xcconfig  =  { 'LIBRARY_SEARCH_PATHS' => '"$(PODS_ROOT)/EstimoteSDK"',
               'HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/Headers/EstimoteSDK"' }
  s.license      = {
    :type => 'Copyright',
    :text => <<-LICENSE
      Copyright 2013 Estimote, Inc. All rights reserved.
      LICENSE
  }
end
```
