### ISSUE TITLE
⚠️ App crashes in relevant numbers after updating to 5.4.0 

### ISSUE THREAD

**Issue by DanielTamm** [iovation/deviceprint-SDK-iOS#36]
We released our app this week, after updating to 5.4.0 as this version seems to fix https://github.com/iovation/deviceprint-SDK-iOS/issues/35. After releasing, we saw a relevant number of crashes in the framework. 

```
Fatal Exception: NSInvalidArgumentException
SecKeyVerifySignature() called with NULL signature
```

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9d94 __exceptionPreprocess
1  libobjc.A.dylib                0x183d0 objc_exception_throw
2  CoreFoundation                 0xf7300 __CFDictionaryCreateGeneric
3  Security                       0x18afc SecKeyVerifySignature
4  FraudForce                     0x169ac (Fehlt UUID a99f822f6e83314d9bdc24e9e5da226f)
5  FraudForce                     0x16594 (Fehlt UUID a99f822f6e83314d9bdc24e9e5da226f)
6  FraudForce                     0xd1d8 (Fehlt UUID a99f822f6e83314d9bdc24e9e5da226f)
7  FraudForce                     0x162b0 (Fehlt UUID a99f822f6e83314d9bdc24e9e5da226f)
8  app                            0x1be2b0 partial apply for closure #1 in closure #1 in IovationFraudForce.generateBlackbox() + 61 (IovationFraudForce.swift:61)
```

**Comment by idrougge** [comment]
This issue has been ignored for months. It is not acceptable to ignore crashes reported by paying customers. Most open source projects have better follow-up and error handling, and this is a commercial package that can cost its (paying) users money for every crash.

**Comment by sara-porter-iovation** [comment]
Hello and thank you for your patience!  5.4.1 was released to resolve this issue.  Please let our Customer Success Team know if this hasn't been resolved for your integration.
