### ISSUE TITLE
iOS17 PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by zhaojb9** [iovation/deviceprint-SDK-iOS#38]
Have you considered responding to PrivacyInfo.xcprivacy?

**Comment by thanospapazoglou** [comment]
@zhaojb9 It has just been added to the latest version [5.6.0](https://github.com/iovation/deviceprint-SDK-iOS?tab=readme-ov-file#v560)

**Comment by zhaojb9** [comment]
@thanospapazoglou 
Many thanks for resolving this issue.
