### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by domenicovoto** [iovation/deviceprint-SDK-iOS#4]
Xcode Version 11.1 (11A1027)
Mac OS Catalina 10.15

Objective-c project

Creating slim frameworks for VALID_ARCHS: arm64 arm64e armv7 armv7s

.....

The domain/default pair of (.........project path...../Frameworks-build/FraudForce.framework/Info.plist, CFBundleExecutable) does not exist
Command PhaseScriptExecution failed with a nonzero exit code

Tested also the demo app, same problem.

**Comment by PratibhaShetty** [comment]
This error comes only in Mac OS Catalina 10.15. I was using Xcode 11 in Mojave. I switched Mac OS to Catalina yesterday. Observed the same issue

The domain/default pair of (.........project path...../Frameworks-build/FraudForce.framework/Info.plist, CFBundleExecutable) does not exist
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by PratibhaShetty** [comment]
This got resolved by upgrading Xcode version to 11.1.

**Comment by powerwolf543** [comment]
I still have same issue.
MacOS 10.15.1
Xcode 10.2.1

**Comment by TerryCK** [comment]
I have same issue,
MacOS 10.15.1
Xcode 10.3

when I try to run command on the terminal with sample
$ defaults read "${OUTPUT_FRAMEWORK_PATH}/Info.plist" CFBundleExecutable

it would show 
"The domain/default pair of /deviceprint-SDK-iOS-master/FraudForce/SDK/FraudForce.framework/Info.plist does not exist"

So I just hard code on both slim-build-frameworks.sh & add-framework-symbols-to-app-archive.sh to workaround 
FRAMEWORK_EXECUTABLE_NAME="FraudForce"

Any ideas?

**Comment by mattr-io** [comment]
Thank you for the feedback, however this forum is not the most efficient way to get support and questions answered. Please contact your iovation Integration Engineer directly on these issues for the most prompt response.

**Comment by interstateone** [comment]
The defaults command seems intended for use with the macOS preferences system. Included in its man page is:

> WARNING: The defaults command will be changed in an upcoming major release to only operate on preferences domains. General plist manipulation utilities will be folded into a different command-line program.

Perhaps Catalina is that upcoming major release 😅 

A better alternative to using defaults is PlistBuddy. If you replace the defaults command in `slim-build-frameworks.sh` with `/usr/libexec/PlistBuddy -c "Print :CFBundleExecutable" "${OUTPUT_FRAMEWORK_PATH}/Info.plist"` then it will return the same value and shouldn't fail with the error quoted above.

**Comment by willhess** [comment]
I am still experiencing this issue with Xcode 11.3 and Mac OS 10.15.2.

**Comment by mattr-io** [comment]
We really appreciate your feedback and we do want to help, but iovation (a TransUnion company) is not going to provide support in this forum at this time. Please contact your iovation Integration Engineer directly on these issues for the most prompt response. They will help you.
