### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ekimia** [iovation/deviceprint-SDK-iOS#5]
Would make the really messy install process much better.

**Comment by CraigSiemens** [comment]
+1 for this. 

It looks like it would be fairly straight forward to do. Just need to add another zip to the GitHub release that contains the framework.
https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

Another option is to serve a JSON file somewhere with links to the zipped framework.
https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification

**Comment by PDXMobileTommy** [comment]
Howdy and thank you for the feedback.
A Carthage JSON file (“Binary Project Specification”) has been added to a branch in our public GitHub repository:
https://github.com/iovation/deviceprint-SDK-iOS/tree/gh-pages
The direct URL to this JSON file, e.g. for use in a Cartfile:
https://iovation.github.io/deviceprint-SDK-iOS/FraudForce.json
A short how-to is available at:
https://iovation.github.io/deviceprint-SDK-iOS/
Cheers,
Tommy

**Comment by ekimia** [comment]
Thanks @PDXMobileTommy ! Will give it a shot soon.

**Comment by ekimia** [comment]
@PDXMobileTommy  I think you also need to specify FBLPromises or whatever the dependency is called in your carthage instructions. Just shipped a new build using your carthage to integrate vs the old way! Thanks again for doing this.
