### ISSUE TITLE
Crash when backbox call

### ISSUE THREAD

**Issue by laurentRedshift** [iovation/deviceprint-SDK-iOS#6]
Hi, 

i have an issue sometimes when FraudForce.blackbox() is called, my app is crashing.
i attached my crash log.
Do you have any idea what's going on and can you help me to fix it?

Thanks

[com.meetic.iphone_issue_crash_d82a111c034542259539e783eb1ff030_DNE_0_v2.txt](https://github.com/iovation/deviceprint-SDK-iOS/files/3809901/com.meetic.iphone_issue_crash_d82a111c034542259539e783eb1ff030_DNE_0_v2.txt)

**Comment by Dave-iovation** [comment]
Hi Laurent,
Could you mail this to clientsupport@iovation.com please?
Thanks,
Dave

**Comment by mark-sanvitale-iovation** [comment]
This issue was addressed in the v5.0.4 release of the SDK.
