### ISSUE TITLE
Add Support for xcframework with Xcode 11

### ISSUE THREAD

**Issue by codecaffeine** [iovation/deviceprint-SDK-iOS#8]
Xcode 11 adds support for the xcframework, which means we don’t have to do the `lipo` dance to extract the correct architecture before building. It would be nice to support this in addition to the "fat" frameworks.

More information can be found here:
* https://developer.apple.com/videos/play/wwdc2019/416/
* https://appspector.com/blog/xcframeworks

I was able to successfully create a FraudForce .xcframework by doing the following:

```sh
lipo FraudForce.framework/FraudForce -extract arm64 -output ../test/arm64/FraudForce.framework/FraudForce
lipo FraudForce.framework/FraudForce -extract x86_64 -output ../test/x86_64/FraudForce.framework/FraudForce
```

To extract the architecture specific frameworks. I then copied over the `Headers`, `Info.plist`, and `Modules` into each of these extracted frameworks.

Finally, I created the xcframeworks by doing:

```sh
xcodebuild -create-xcframework -framework arm64/FraudForce.framework -framework x86_64/FraudForce.framework -output FraudForce.xcframework
```

I’ve tested this successfully with a simulator and soon I’m going to test with a device.

The parts that I’m less sure about is signing (since your original universal framework is signed by you) and handling debug symbols. It would just be nice to have a simpler distribution strategy that Apple now supports.

**Comment by simonpierreroy** [comment]
A side note, this may work but is really bad. 

The compiler probably never build this using `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`, meaning that the compiler never created a `.swiftinterface` and is using `.swiftmodule` (meaning any swift code cannot build on new version of the toolchain with module stability). In this scenario, this SDK maybe an `objc` code base only, so you are fine. But other `objc` requirements for distribution like `@objc' static property in extension of subclass of 'X' requires iOS 13.0.0` or other validation were not validated. Be careful for runtime crashes with this / future crashes with new runtimes.

**Comment by ashley-campbell-iovation** [comment]
Hello!

We expect to release an XCFramework soon and appreciate the feedback.

Thanks!
Ashley
