### ISSUE TITLE
Multiple submissions from the same session

### ISSUE THREAD

**Issue by EralpB** [iovation/deviceprint-SDK-iOS#9]
is it OK to generate the blackbox key once per session? so if user submits 2 different distinct piece of content, would it be OK to submit the same iovation key?

or must it be generated PER request (per content)?

**Comment by PDXMobileTommy** [comment]
Howdy EralpB - Please submit questions directly to the Customer Support team assigned to you or your company. This will ensure that all required parties are aware of your question and this will help us focus towards an expedited answer/resolution.  Cheers, Tommy
